
baseurl:
url: https://xiaokuicui.github.io
date_format: "ordinal"
title: 持续更新中....
subtitle: "打码改变人生"
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: XiaoKui
github_username: xiaokuicui
location: Beijing, China
email: xiaokui.cui@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于



markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xiaokuicui.github.io

#Comments
comments_provider: gitalk
gitalk:
    owner: xiaokuicui
    repo: xiaokuicui.github.io
    clientID: f06ff552466b55142032
    clientSecret: e2bc29cfc743efadb34732ce9f09ec5a7338c674



#Google Analytics
google:
    analytics_id: UA-111867840-1
